apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-deployment
  namespace: super-mario
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mario
  template:
    metadata:
      labels:
        name: mario
    spec:
      containers:
        - name: mario
          image: sevenajay/mario
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mario-service
  namespace: super-mario
spec:
  type: NodePort
  selector:
    name: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mario-ingress
  namespace: super-mario
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mario-service
                port:
                  number: 80